# Generated by Django 2.0.8 on 2018-10-25 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='imgpath',
        ),
    ]
