# Generated by Django 2.0.8 on 2018-10-29 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankApp', '0002_remove_register_imgpath'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='Age',
            new_name='customerAge',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='userName',
            new_name='customerName',
        ),
    ]
